#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-azure-storage-java
Version  : 7.0.0
Release  : 1
URL      : https://github.com/Azure/azure-storage-java/archive/v7.0.0.tar.gz
Source0  : https://github.com/Azure/azure-storage-java/archive/v7.0.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/microsoft/azure/azure-storage/7.0.0/azure-storage-7.0.0.jar
Source2  : https://repo1.maven.org/maven2/com/microsoft/azure/azure-storage/7.0.0/azure-storage-7.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-azure-storage-java-data = %{version}-%{release}

%description
# Microsoft Azure Storage SDK for Java
This project provides a client library in Java that makes it easy to consume Microsoft Azure Storage services. For documentation please see the Microsoft Azure [Java Developer Center](http://azure.microsoft.com/en-us/develop/java/) and the [JavaDocs](http://azure.github.io/azure-storage-java/).

%package data
Summary: data components for the mvn-azure-storage-java package.
Group: Data

%description data
data components for the mvn-azure-storage-java package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-storage/7.0.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-storage/7.0.0/azure-storage-7.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-storage/7.0.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-storage/7.0.0/azure-storage-7.0.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/microsoft/azure/azure-storage/7.0.0/azure-storage-7.0.0.jar
/usr/share/java/.m2/repository/com/microsoft/azure/azure-storage/7.0.0/azure-storage-7.0.0.pom
